name: chatapps
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD-root}
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: chatapps
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - chatapps
    volumes:
      - ./data/mysql:/var/lib/mysql
      # - ./shopping.sql:/docker-entrypoint-initdb.d/shopping.sql
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    networks:
      - chatapps

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
  nginx:
    image: nginx:latest
    ports:
      - "8888:8888"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - chatapps

networks:
  chatapps:
