name: chatapps
services:
  mysql:
    image: mysql:latest
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./data/mysql:/var/lib/mysql
      # - ./shopping.sql:/docker-entrypoint-initdb.d/shopping.sql
    networks:
      - chatapps  

  cassandra:
    image: cassandra:latest
    env_file:
      - ./.env
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    networks:
      - chatapps

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_GATEWAY_PORT}:8888"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - chatapps

  discovery-server:
    build: ./discovery-server
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - ${DISCOVERY_SERVER_PORT}:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - chatapps

  chat-api:
    build: ./chat-api
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - ${CHAT_API_PORT}:8081
    networks:
      - chatapps
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5


  chat-server:
    build: ./chat-server
    depends_on:
      cassandra:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - ${CHAT_SERVER_PORT}:8083
    networks:
      - chatapps
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5


  chat-ui:
    build: ./ui
    depends_on:
      chat-api:
        condition: service_healthy
      chat-server:
        condition: service_healthy
    ports:
      - ${CHAT_UI_PORT}:3000
    env_file:
      - ./.env

networks:
  chatapps:
