# application.yml
spring:
  application:
    name: ${CHAT_API_NAME:chat-api}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_REGISTER:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true