server:
  port: ${DISCOVERY_SERVER_PORT:8761}
  output:
    ansi:
      enabled: ALWAYS
eureka:
  client:
    register-with-eureka: false # Không đăng ký chính nó với Eureka
    fetch-registry: false # Không lấy danh sách dịch vụ (vì nó là server)

spring:
  application:
    name: ${DISCOVERY_SERVER_NAME:discovery-server}