#server:
#  port: 8080
#spring:
#  output:
#    ansi:
#      enabled: ALWAYS

# application.yml
spring:
  application:
    name: chat-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_NAME:localhost}:${DISCOVERY_SERVER_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true